#!/usr/bin/env sh

# Arbitrary but unique message tag
msgTag="Gamemode"

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')

if [ "$HYPRGAMEMODE" = 1 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:shadow:enabled 0;\
        keyword decoration:blur:enabled 0;\
        keyword general:gaps_in 0;\
        keyword general:gaps_out 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
    hyprctl keyword windowrule "opacity 1.0, ^(com.mitchellh.ghostty)$"
    dunstify -a $msgTag -u low -i colors-chromagreen -h string:x-dunst-stack-tag:$msgTag $msgTag "on"
    exit
fi

hyprctl reload
dunstify -a $msgTag -u low -i colors-chromared -h string:x-dunst-stack-tag:$msgTag $msgTag "off"
