#!/usr/bin/env bash

if [[ $# -eq 0 ]] ; then
  echo "" | \
    rofi -dmenu rofi -theme-str '#mainbox { children: [ "inputbar" ]; }' -p "Google:" | \
    xargs -I{} uwsm app -- xdg-open https://www.google.com/search?q={}
else
 uwsm app -- xdg-open https://www.google.com/search?q="$1"
fi
