#!/usr/bin/env sh

# Get a list of used workspaces (numbers only)
USED_WS=$(hyprctl workspaces -j | jq '.[].id' | sort -n)

# Start from 1 and find the first unused workspace
for i in $(seq 1 20); do
    if ! echo "$USED_WS" | grep -q -x "$i"; then
        hyprctl dispatch workspace "$i"
        exit 0
    fi
done

