#!/usr/bin/env bash

userId=$(id -u)

export XDG_RUNTIME_DIR=/run/user/$userId
export WAYLAND_DISPLAY=wayland-1
export DBUS_SESSION_BUS_ADDRESS=unix:path=$XDG_RUNTIME_DIR/bus

swww kill
sleep 0.1
uwsm app -- swww-daemon &
