#!/usr/bin/env bash

# Arbitrary but unique message tag
msgTag="VolumeChange"

if [[ "$@" == "mute" ]]; then
  wpctl set-mute @DEFAULT_SINK@ toggle > /dev/null 2>&1 &
elif [[ "$@" == "mutemic" ]]; then
  wpctl set-mute @DEFAULT_SOURCE@ toggle > /dev/null 2>&1 &
else
  wpctl set-volume @DEFAULT_SINK@ "$@" > /dev/null 2>&1 &
fi

sleep 0.01

volume="$(wpctl get-volume @DEFAULT_SINK@ | sed -E 's/.*: ([0-9]+\.[0-9]{2})$/\1/; s/^0*([0-9]*)\.([0-9]{2})$/\1\2/; s/^$/0/; s/^0+$/0/; s/$//')"
muted="$(wpctl get-volume @DEFAULT_SINK@ | sed -E 's/.*\[([A-Z]+)\]/\1/')"

if [[ "$@" == "mutemic" ]]; then
  dunstify -a "changeVolume" -t 1000 -u low -i microphone-sensitivity-muted "Mic (un)muted"
elif [[ "$muted" == "MUTED" ]]; then
  # Show the sound muted notification
  dunstify -a "changeVolume" -t 1000 -u low -i audio-volume-muted -h string:x-dunst-stack-tag:$msgTag "Volume muted" 
else
  # Show the volume notification
  dunstify -a "changeVolume" -t 1000 -u low -i audio-volume-high -h string:x-dunst-stack-tag:$msgTag -h int:value:"$volume" "Volume: ${volume}%"
fi
