#!/usr/bin/env bash

alias dotgit='/usr/bin/git --git-dit=$HOME/Git/vicnotor/dotfiles-xx/ --work-tree=$HOME'

git clone git@github.com:vicnotor/dotfiles-xx.git "$HOME"/Git/vicnotor/dotfiles-xx

rm -rf .profile .bashrc

dotgit checkout
dotgit config --local status.showUntrackedFiles no
