#!/usr/bin/env bash

name="home"
directory="$HOME"
output="/dev/null"

debug() {
    echo "$@" &>"$output"
}

no_tmux() {
    [[ -z $TMUX ]]
}

has_session() {
    tmux has-session -t "$1" 2>/dev/null
}

new_session() {
    tmux new-session -s "$1" -c "$2" -d
}

new_session_systemd() {
    # app2unit -- tmux new-session -s "$1" -c "$2" "$SHELL"
    tmux new-session -s "$1" -c "$2" "$SHELL"
}

if has_session "$name"; then
    if no_tmux; then
        debug "Attaching to tmux session $name"
        tmux attach-session -t "$name"
    else
        debug "Switching to tmux session $name"
        tmux switch-client -t "$name"
    fi
else
    debug "Creating new session $name"
    if no_tmux; then
        new_session_systemd "$name" "$directory"
        tmux attach-session -t "$name"
    else
        new_session "$name" "$directory"
        tmux switch-client -t "$name"
    fi
fi
